mode: rule
log-level: error

hosts:
  ntc.party: 130.255.77.28

dns:
  enable: true
  enhanced-mode: redir-host
  nameserver:
    - https://dns.nextdns.io
  nameserver-policy:
    "+.ts.net": "ts://tailscale"
  use-system-hosts: true
  fake-ip-filter:
    - "*.lan"
    - "+.ts.net"
    - geosite:connectivity-check

proxy-providers:
  proxy-list:
    type: inline
    payload:
      - name: "Private placeholder"
        type: direct
        client-fingerprint: firefox

proxy-groups:
  - name: proxy
    type: select
    use:
      - proxy-list
    
rule-providers:
  apple-system:
    type: inline
    behavior: classical
    payload:
      - DOMAIN,api.smoot.apple.com
      - DOMAIN,captive.apple.com
      - DOMAIN,xp.apple.com
      - DOMAIN,configuration.apple.com
      - DOMAIN,guzzoni.apple.com
      - DOMAIN,smp-device-content.apple.com
      - DOMAIN,aod.itunes.apple.com
      - DOMAIN,mesu.apple.com
      - DOMAIN,api.smoot.apple.cn
      - DOMAIN,gs-loc.apple.com
      - DOMAIN,mvod.itunes.apple.com
      - DOMAIN,streamingaudio.itunes.apple.com
      - DOMAIN-SUFFIX,ess.apple.com
      - DOMAIN-SUFFIX,push-apple.com.akadns.net
      - DOMAIN-SUFFIX,push.apple.com
      - DOMAIN-SUFFIX,lcdn-locator.apple.com
      - DOMAIN-SUFFIX,lcdn-registration.apple.com
      - DOMAIN-SUFFIX,ls.apple.com
      - PROCESS-NAME,trustd
      - PROCESS-NAME,netbiosd

rules:
  - DOMAIN-SUFFIX,ts.net,tailscale
  - IP-CIDR,100.64.0.0/10,tailscale,no-resolve
  
  - GEOIP,LAN,direct,no-resolve
  - GEOSITE,connectivity-check,direct
  - GEOSITE,category-ntp,direct
  - DOMAIN,guzzoni.apple.com,proxy
  - RULE-SET,apple-system,direct
  - GEOSITE,icloudprivaterelay,direct
  - DOMAIN,_test.local,reject

  # Kino.pub
  - DOMAIN-SUFFIX,cdntogo.net,direct
  # Docker mirrors
  - DOMAIN-SUFFIX,mirror.gcr.io,direct

  # Aliexpress payments
  - DOMAIN-SUFFIX,inplat-tech.com,direct

  # OneDrive
  - DOMAIN-SUFFIX,my.microsoftpersonalcontent.com,direct
  # Misc
  - DOMAIN-SUFFIX,vfsglobal.com,direct
  - DOMAIN-SUFFIX,izi.me,direct
  - DOMAIN-SUFFIX,iziyo.xyz,direct

  # Licard
  - DOMAIN-SUFFIX,licard.com,direct
  # Tricolor
  - DOMAIN-SUFFIX,tricolor.tv,direct

  # Misc
  - DOMAIN-SUFFIX,habr.com,direct
  - DOMAIN-SUFFIX,wylsa.com,direct
  - DOMAIN-SUFFIX,wishmaster.me,direct
  - DOMAIN-SUFFIX,quantum-a.io,direct
  - DOMAIN-SUFFIX,lmru.tech,direct
  - DOMAIN-SUFFIX,imdt.pro,direct
  - DOMAIN-SUFFIX,fintechru.org,direct
  - DOMAIN-SUFFIX,rozetked.me,direct
  - DOMAIN-SUFFIX,curator.pro,direct
  - DOMAIN-SUFFIX,netcraze.cloud,direct
  - DOMAIN-SUFFIX,moscowtransport.app,direct
  
  # Russia
  - GEOSITE,category-ru,direct
  - GEOIP,RU,direct,no-resolve

  # Everything else
  - MATCH,proxy
